### PR TITLE
Add parser tests using multi-words

### PR DESCRIPTION
**Pull request by mausimus**
I've added a range of tests for using multi-words in the parser; apologies if it looks a bit overkill but I think the issues around the parsing function we've recently found warrant a comprehensive approach. These tests need current master to fully pass.

### CODE REVIEW

**Comment by ericoporto** [comment]
Thanks, this looks alright, I just noticed that for some reason some unrelated graphics rendering tests are failing so I will just give a check on that.

**Comment by mausimus** [comment]
Thanks, no it doesn't need that new PR at the moment; I have written some extra tests after I found that bug though, should I add them here now or wait until the fix PR gets merged to ags master?

**Comment by ivan-mogilko** [comment]
> I have written some extra tests after I found that bug though, should I add them here now or wait until the fix PR gets merged to ags master?

It makes sense to add new tests right away, if they fail that would be also useful, that's what tests are for :).

**Comment by mausimus** [comment]
Ok no problem, I added the test that https://github.com/adventuregamestudio/ags/pull/2443 fixes.

**Comment by ericoporto** [comment]
@mausimus I merged mostly because I was curious to see this running in you PR, but now I notice I don't understand a specific `"please"` wording in this function. Can you explain me what this function is doing?

```AGS Script
void TestParserSaid(const string saidWords, const string inputText, int expectedResult)
{
    Parser.ParseText(inputText);
    String testName = String.Format("TestParserSaid: Said() '%s' with ParseText() '%s' should be %d", saidWords, inputText, expectedResult);

    if(expectedResult)
      tap.ok(Parser.Said(saidWords), testName);
    else
      tap.nok(Parser.Said(saidWords), testName);

    // test with extra content at the end
    String extendedWords = String.Format("%s rol", saidWords);
    String extendedText = String.Format("%s please", inputText);
    Parser.ParseText(extendedText);
    testName = String.Format("TestParserSaid: Said() '%s' with ParseText() '%s' should be %d", extendedWords, extendedText, expectedResult);

    if(expectedResult)
      tap.ok(Parser.Said(extendedWords), testName);
    else
      tap.nok(Parser.Said(extendedWords), testName);
}
```

**Comment by mausimus** [comment]
Sure, I added this "extended" pass to make sure there's no difference if the words are at the end of the input or not (I've found some issues relating to parsing at the very end of the input earlier on), so it just adds "rol" to the pattern and "please" ignored word to the input, which shouldn't have any impact on the parsing result.

**Pull request merged**
